rvm:
  - 2.0.0
  - 2.1

# http://docs.travis-ci.com/user/caching/#Enabling-Bundler-caching
cache: bundler

branches:
  only:
    - master

before_install:
  - 'cp config/database.yml.sqlite3 config/database.yml'

before_script:
  - 'RAILS_ENV=test bundle exec rake setup'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: 'RAILS_ENV=test bundle exec rake db:drop db:create db:migrate spec konacha:run && RAILS_ENV=production bundle exec rake assets:precompile '
